# Generated by Django 5.1.7 on 2025-03-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_paterno', models.CharField(max_length=50)),
                ('Apellido_materno', models.CharField(max_length=50)),
                ('Rut', models.CharField(max_length=10)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo', models.EmailField(max_length=50)),
                ('Sexo', models.CharField(max_length=50)),
                ('Fecha_nacimiento', models.DateField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_hora', models.DateTimeField()),
                ('Motivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Raza', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Fecha_nacimiento', models.DateField(max_length=50)),
                ('Sexo', models.CharField(max_length=50)),
                ('Especie', models.CharField(max_length=50)),
                ('Peso', models.FloatField(max_length=3)),
                ('Edad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snippets.persona')),
            ],
            bases=('snippets.persona',),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snippets.persona')),
                ('Especialidad', models.CharField(max_length=50)),
            ],
            bases=('snippets.persona',),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Fecha_hora', models.DateTimeField()),
                ('ConsultaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='MascotaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='Id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.cliente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='VeterinarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.veterinario'),
        ),
    ]
